# the following envvars added via travis admin panel
# AWS_ACCESS_KEY
# AWS_SECRET_ACCESS_KEY
# EARTHDATA_USER
# EARTHDATA_PASS

language: python

python:
- '2.7'

services:
  - docker

install:
  - pip install awscli docker-compose==1.8.0
  - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
  - echo "EARTHDATA_PASS=$EARTHDATA_PASS" >> .env
  - echo "EARTHDATA_USER=$EARTHDATA_USER" >> .env
  - mv .env modispds/.env
  - docker-compose build

script:
- docker-compose run test
