
language: python

python:
- '2.7'

services:
- docker

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
    # AWS_ACCESS_KEY_ID
  - secure: AZORzNQyuiUemlQZ8gwi53Yjuw0oVMECXCys+RfP5g4rKY3SBap8oqgbL1AYzw39oRuAClFwGbi/pvn75BN2SDex5WjVrMaYfv+pplJ83WwCMDbSmVf5p6kdzWt0zNeI8WbVmLAp7t7BPEOKLMm8NgRyzMVGMnbRk+Jl0kIh1uw8TY/Ss9zVTjnpdtg9PhP3UkTcav+15oq1SzEilJOd6pOFRZPrgeY6hNDw+oQOrdBiKJ1piQirNvXurpwrx1jB+emxkVWoaWLTpkVb4baLCbtU94vx0eHaXWiadcmvrMw5rXUVddYWNquvFuB/BmkXBWl42N/Ah0/WEJFOHJL6WpIgk6lgdInjOT6O/tw0KUN58JT2TRAiSO8pH37tGGl3rvY/Ngt5ZTdFxN5KM9iO68sw/RyrWSXZfxcJQApgwxZDT2RPofexjuYvZgiAtsyDAOJikmlBrqQrv+8CQFVLKcUldk6A1LHRYYJuLvlg0IdrDJIMUGety8RgCq/eSVlCcizbb/O4/hOA3ZILex9ZCpZGmK9znATG+POcMOMrBfQA5kN9YneTKuB02lqcgnSZdY08sMJnFX2V8mGHIYiNczUaMxkyz6oy2y0ciLzM4d9BQjd8SFmJNHmXTSDc4AU4vW/MOtg19GIiuCrf4nAR9dWE+TAmCj8FoFeiZMnpO6g=
    # AWS_SECRET_ACCESS_KEY
  - secure: ugjPTRpOUrR0H807xAQ+aqJ7nOa7frkooj+Wf5Rqxw6V/ifjrPIMC/08bRZ64L27bj5apP1o3roaVQr8XuGmIx8Q8Z2BhFTOOiBrFbRd2i5oq7+SXcqHvMNFWsSpgCd8V2FdUuSodPPgfdLw2fldXOwzn8l5844wc8nO8qY32lQv4wX+hBqKHcx+GRIUcn7FjBrzTT6yxGylZq5vp6xGFWWgmsAoXCJn+Ccow4U+tHX2fEmYEgotORs2ZXSGs8NNZORaVhJzGFBextpAx8lbP7hFagzEOeElzZGezps7GgY+p8Qdgx+1BIEVlnpWizsRWbhn8vVx1AoQPZP2Fayx+RCSSwF3jE5zgp+XKX6Xd/tuCsyQ+cmNYE8u7NCkT6Ot/ATRtARJItSbATYdHt/GA71+xyCaaHrBf3a9QfYEwXzDO9EF4JBaV7oc58gMRv6PDSMWn9xisLrGP1+RGR3pJS4Cf5xRGFmaM7RzttWfMmDJH5NuQAKxYOztJibNbqafaQiIcZyjgb3qOmiHg43qizH9bfF8X8zuQCRj8KbOqOHJ6/sv+pBktXX/nvOzr475P95B1G+VXiTIzsDxzWPB427m+ehmIkl3gV5MzY7KeM3zbxq6seef7XHdUYEQTSHV6Xz8yUZHDjOP57awbPvrpcTKYnUTAQoyeh/quCMWTJ8=
  - EARTHDATA_USER=devseed
    # EARTHDATA_PASS
  - secure: QgmUCPHfY2vAr+zqqY9HjLDhmwoGKzB+iUYhoat3V+hkzBxFwCg4I8QjESbLeC/ysQ6SFQdb+Kw4/4z1K+BQOmG3QcGuCI9us02FDLfEDicoYcQr+wRGPAvIdaZ243eKN50fP0diZffQTbefckvoq/qaucz6CMXFnDAQ6Jr93zBPgrVxYCeTIdw9d1KAqA5JCaDTbNBKCLGLEjtmlCsfpXwCWgQsd+iVgISm+M70EZxpH/Ycl210F2AG+jZcTtmHenk5LlgZ9KYpYOAoMQAuOgDUqDpuFHwfQjRL2wqoGgiyxcVyCWKwFY3TX/cm6BQxUOZ+Mnyxqd7k/k77REanjKYFwn9UXE9JOCZgYfNn6z6UlHbedaWTy7VFjwDoX9dMQNFHfoWiBosdug2n7n4uiFh6Na4JyCITmaQErGR7+kMrYV68wTkha4w7DN+pqd3Qbuju4DcW+RBGOpGOtrV5dgBgAPpScKy5Bd6x+ierRsXVF1tRgnmUQqvzvJDwumkkshGwRblMuolNHCKjTBjmfavlNlFI0l8eJxwkLN+7AeKFcVg9tGfXpdfD0s0vNmO5j0Pmv12yTy8DQNHYFBvZ298NkvXdMVo74JSR0wQbpstU5QqF16//aG/r0XjvDHl6bA0UB6Wdm8GMKFBZ9gUixFKAWnqiZjeM79fS3tp98nI=
    # DOCKER_EMAIL
    - secure: "0Zhj+lljbv9C3SQSXR5lMVE6yI0C8Ju1oTpFNeFEz3Yc01OzviEE5I1VFBPKkKd3nOoA/Vbe3pjxQ5bB63JXcJQgCTOB6XkcTWEeDOhiyu8ox/wMaX5VbwD3RRrBu73wP1JHAMkUunuiFnG/IUAVlQD1cZendHePInqA16mqG3vnb6QBNE00rWLg2fu2fU4gyLkR2igZt6cweiAC40mtCWHJRJcUCzb9/2+JYy5Ge7pHaNiy5s/jHHWRotRO9RGkbRpmkvN4MguCBfFZl/DQ2s6PKgu7P1vjTu2RtbCAOfqkUFnV2N2j0Vu0aSIUNW1JtuQTn3ectU9eWWBxUuGhNhXvKDmglelwWIHRrLXvEcPL8LtULQZlB0tO6BejZbjur7fg2ogyJ0lHq8AdV5zoKu42NIjqU+ssVEYOqHWj99Z9ip/xOI8NIFVnup8negMoMDzuGvlMCqCrAcM5SA7+4l2PLIqCnX/cmscjvB87NgCkh3s7Nhjd4EEvUbJV/SmuJddr87AYrw9rygiHZP/OvVhsKsvAhtRxrUsfYlurBIPSH5GF5uQlc9GGfJbzOuvI397TdTteB0X4tXiyRDv1eiOSXHArvNLRw2/pbxtQhB5UYrkdUmHk3oQgjqlW9uK6EOp8PNIQnjpz+eYGyLY9ZwOb9k0W5ZQ/MQF3cEaW30U="
    # DOCKER_USER
    - secure: "yybjt0Nho4V+20iSNhsfZbsx/owa9Pu6yOVHqKMXfUqiq/HiDEScmh0h4w1l1ORrW7kSz6UcLuPFh4q+Okeij6BIFjNQ6iq0hMrwyj7GR6DVGZtoYVrbGTlsxKba2FSdZRN413i5jQ3jY+YzEDs+Q3mT/5+gdjyE8tGx99sDk9FXYmrrzyH3//OOlM8T4ZQgxCKwpj0Vvcrhd9Gw0x4/GFV2WOVsTdRkYw2m142BUX5w+VVVaIHZyT1FwZ2NPmJHg5TzqF/hgOmNAVpK1bG/xruJYx0VRdmMIqj8h8A6QTKI/xoKdzZPwlG6R7h1toWzC5ONv9oHZnifrPOGHKRNW070u7PH58FfSn2eVjiI+IaRoR3Vs8MEa+FaDf9CIYHlu1pioutE4TDAoWUPeN/+T7wcQ+pck8vXk33J3SVQl0lxg9ahdQ7joHD++OlA25F7KHD6cie3OWINDHINTO0JgYRHI58F/9dew6UqF7eAdMu/694XchmlgqTmT0MwqfndTJ1IHkXTXacPvAaIvQoe40kUSuayPFvUjQjiNXl5zhbPy63pCgNSLLdWWBJodN/2nh2A9irC6Fwzk7X8fnRUaLRS3lzha67BQtSt15/G8nLLynTo+jmZYwApm94nVcO4Nhi1qQ8JZ5qwrMPfglTyIPzMYtmKLa8y6xzwdizkO/w="
    # DOCKER_PASS
    - secure: "vjOfqUroAbvGNpCBpKeX9dC3wM8LWKLQ79XzIoGzdTgsSoOvb7OZ8qEBkw/xb2Yo85Sbd56j1EAxbwv6LvpAsH/u/EVPxFQfcLt2uqFTL0jbZ0e0w6g9IjEHUPfBwb20VhPXxOmmUIxOQmAsqzNFOrBsm6Wv/xTHohc73ESpFFFJUZSlA29sj7vXQT9GWZj61mVZARofc+7abfb+OhGl/6F5e9JDsli89CBTS8He50L7Hz8fC+NirjHq+MAyhGXMg73jJqIlOfVSTq4P4WWBikE3f6Iv+VA3rHK7/xhhCZccZMMfa3EN+xMewjbnD7DLL4456OBAZFgz7F9kjsJmwTD6YXcbDcfTvPhRnhxIpPrbZkOOwtFV14qxJMco5gauRs92EBRYFFgtLOjOmT7IFNdZNPzmYsiVQuwE5rAfiYeFDcRWqHfAxyZ6foo4piE7djwDV9VjDBQ8kW/7s0z+aBQTQtz8cK2av30FQBM+hA/8v+f8sMtrmo8QN2JHk2omUh8BB5Nl5iez2YLPIorHAOmxYnENnmr0GAF5jgappg0Ecb84pWWGKTX9CBoSNHYr7Ne2vHO6sWC00Uomh0PLMCJ50c3N2KCH/mfGIM7f+LeqqnHVPj4i0s8cyxsOSLsObCkJp1sjRESa2u7eZjSeFZFz+7nSOrm4GjmfbUjmsPg="

install:
- pip install awscli docker-compose==1.8.0
- echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
- echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
- echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
- echo "EARTHDATA_PASS=$EARTHDATA_PASS" >> .env
- echo "EARTHDATA_USER=$EARTHDATA_USER" >> .env
- mv .env modispds/.env
- docker-compose build

script:
- docker-compose run test

deploy:
- provider: script
  skip_cleanup: true
  script: 
      docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      docker-compose push
  on:
      branch: master
