language: python

python:
- '2.7'

services:
  - docker

env:
  global:
  - DOCKER_COMPOSE_VERSION=1.8.0
  - AWS_ACCESS_KEY_ID=AKIAI55R6SJ4ORRFFKRA
  - AWS_DEFAULT_REGION=us-east-1
  - EARTHDATA_USER=devseed
  # the following envs added via travis admin panel
  # AWS_SECRET_ACCESS_KEY
  # EARTHDATA_PASS

install:
  - pip install awscli docker-compose==1.8.0
  - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
  - echo "EARTHDATA_PASS=$EARTHDATA_PASS" >> .env
  - echo "EARTHDATA_USER=$EARTHDATA_USER" >> .env
  - mv .env modispds/.env

script:
- docker-compose run test
