version: '2'

services:

  dev:
    build:
        context: .
        dockerfile: Dockerfile-base
    image: 'astrodigital/modispds:base'
    entrypoint: /bin/bash
    volumes:
      - '.:/work'

  latest:
    build:
        context: .
    image: 'astrodigital/modispds:latest'
    entrypoint: /bin/bash

  test:
    image: 'astrodigital/modispds:base'
    entrypoint: bash -c 'nosetests --with-coverage --cover-package modispds --cover-inclusive --with-timer -v -s;'
    working_dir: /work
    volumes:
      - '.:/work'

  ingest:
    image: 'astrodigital/modispds:latest'
    entrypoint: 'modis-pds'
    working_dir: /work
    volumes:
      - '.:/work'

